"""The guard installer, tested — especially that a successful install actually fires.

The bug this suite exists for: `install.py` wrote to `<git-dir>/hooks`, a hardcoded
path, and never consulted `core.hooksPath`. Where that is set — beads, husky,
lefthook — git stops reading `.git/hooks` entirely, so the installer printed a
checkmark, the file existed, `ls .git/hooks/` showed it, and the hook was dead.

Every test builds a real git repository. Mocking `git` here would be worse than no
test at all: the defect *was* a wrong belief about git's behavior, and a mock would
have encoded that same belief and passed.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

SHELF = Path(__file__).resolve().parents[1]
INSTALL = SHELF / "tools" / "hooks" / "install.py"

VERIFIED, REFUSED, COULD_NOT_VERIFY = 0, 1, 2

_BEADS_HOOK = """\
#!/usr/bin/env sh
# --- BEGIN BEADS INTEGRATION v1.1.2 ---
bd hooks run pre-commit "$@"
# --- END BEADS INTEGRATION v1.1.2 ---
"""

_PRECOMMIT_HOOK = """\
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
"""

_HUSKY_HOOK = """\
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npm test
"""

_LEFTHOOK_HOOK = """\
#!/bin/sh
# LEFTHOOK file generated by lefthook
lefthook run pre-commit
"""

_HANDWRITTEN_HOOK = "#!/bin/sh\necho my own hook\n"


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "t@example.invalid")
    _git(tmp_path, "config", "user.name", "Test")
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "c"\nversion = "0.1.0"\n')
    _git(tmp_path, "add", "pyproject.toml")
    _git(tmp_path, "commit", "-qm", "init")
    return tmp_path


def _install(repo: Path, *, shelf_home: str | None = None, home: str | None = None) -> subprocess.CompletedProcess[str]:
    # HOME gets its own directory, never the repo: tools legitimately scribble under
    # $HOME (macOS `Library/`), and that would masquerade as the installer dirtying
    # the working tree in the read-only test below.
    env = {"PATH": "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin"}
    env["SHELF_HOME"] = str(SHELF) if shelf_home is None else shelf_home
    env["HOME"] = home if home is not None else str(repo.parent / "home")
    Path(env["HOME"]).mkdir(parents=True, exist_ok=True)
    return subprocess.run(
        [sys.executable, str(INSTALL), str(repo)],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )


def _hooks_dir(repo: Path) -> Path:
    out = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--git-path", "hooks"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    p = Path(out)
    return p if p.is_absolute() else repo / p


def _use_hookspath(repo: Path, name: str = ".beads/hooks") -> Path:
    d = repo / name
    d.mkdir(parents=True, exist_ok=True)
    _git(repo, "config", "core.hooksPath", name)
    return d


# --- path resolution (D1) -------------------------------------------------


def test_installs_where_git_actually_looks_when_hookspath_is_set(repo: Path) -> None:
    hooks = _use_hookspath(repo)

    result = _install(repo)

    assert result.returncode == VERIFIED, result.stderr
    assert (hooks / "pre-commit").exists(), "guard went somewhere git will never read"
    assert not (repo / ".git" / "hooks" / "pre-commit").exists()


def test_installs_to_git_hooks_when_hookspath_is_unset(repo: Path) -> None:
    """Regression guard for every consumer that has no core.hooksPath."""
    result = _install(repo)

    assert result.returncode == VERIFIED, result.stderr
    assert (repo / ".git" / "hooks" / "pre-commit").exists()


def test_reinstall_is_idempotent(repo: Path) -> None:
    _use_hookspath(repo)
    first = _install(repo)
    body = (_hooks_dir(repo) / "pre-commit").read_text()

    second = _install(repo)

    assert first.returncode == second.returncode == VERIFIED
    assert (_hooks_dir(repo) / "pre-commit").read_text() == body


def test_reinstall_preserves_content_another_tool_chained_after_the_guard(repo: Path) -> None:
    """Found for real, re-onboarding a2kay with beads: `bd init` detects the guard as a native
    hook and chains its own pre-commit integration AFTER it in the same file. A naive reinstall
    that overwrites the whole file the moment MARKER is present would silently delete that
    chained block on the very next re-run of onboarding — exactly what happened.
    """
    assert _install(repo).returncode == VERIFIED
    hooks = _hooks_dir(repo)
    hook = hooks / "pre-commit"
    hook.write_text(hook.read_text() + "\n# --- BEGIN BEADS INTEGRATION v1.1.2 ---\necho chained\n# --- END BEADS INTEGRATION v1.1.2 ---\n")

    result = _install(repo)

    assert result.returncode == VERIFIED
    body = hook.read_text()
    assert "BEGIN BEADS INTEGRATION" in body, "reinstall deleted the chained block"
    assert "echo chained" in body


def test_reinstall_migrates_the_pre_begin_end_format_without_losing_chained_content(repo: Path) -> None:
    """The pre-BEGIN/END exec-based template was live only briefly this session, but it was
    already committed into a real consumer's history (a2kay) before this fix landed -- so a
    fresh clone's first re-run genuinely hits this, not hypothetically. A naive migration that
    falls back to a full overwrite whenever the new markers aren't found would silently repeat
    the exact chained-content loss this format change exists to fix.
    """
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    hook = hooks / "pre-commit"
    old_format = (
        "#!/bin/sh\n"
        "# shelf-guard (no-local-shelf-source) — managed by the shelf installer; safe to re-run.\n"
        'SHELF="${SHELF_HOME:-../shelf}"\n'
        '[ -d "$SHELF" ] || SHELF="$HOME/Workspaces/shelf"\n'
        'GUARD="$SHELF/tools/hooks/forbid-local-shelf-source.py"\n'
        '[ -f "$GUARD" ] && exec python3 "$GUARD"\n'
        "exit 0   # guard unavailable (shelf not cloned) -> do not block\n"
        "\n# --- BEGIN BEADS INTEGRATION v1.1.2 ---\necho chained\n# --- END BEADS INTEGRATION v1.1.2 ---\n"
    )
    hook.write_text(old_format)
    hook.chmod(0o755)

    result = _install(repo)

    assert result.returncode == VERIFIED
    body = hook.read_text()
    assert "BEGIN BEADS INTEGRATION" in body, "migration deleted the chained block"
    assert "echo chained" in body
    assert "exec python3" not in body, "migration should replace the old exec-based span, not just prepend"


def test_content_chained_after_the_guard_actually_executes_when_the_guard_passes(repo: Path) -> None:
    """The deeper bug behind the one above: the guard body used to end in `exec python3
    "$GUARD"`, which REPLACES the shell process on success -- so anything appended after it in
    the same hook file was unreachable dead code from the moment it was chained, independent of
    any reinstall. Proven here by actually running the hook (guard passing, nothing offending
    staged) and checking a file the chained content writes.
    """
    assert _install(repo).returncode == VERIFIED
    hooks = _hooks_dir(repo)
    hook = hooks / "pre-commit"
    sentinel = hooks / "chained-ran.txt"
    hook.write_text(hook.read_text() + f"\necho ran > {sentinel}\n")

    # SHELF_HOME must be explicit here too (see the sibling test above): without it, an
    # environment with no ~/Workspaces/shelf hits the guard's fail-open path instead of
    # actually passing, and this test would pass for the wrong reason.
    env = {**os.environ, "SHELF_HOME": str(SHELF)}
    ran = subprocess.run([str(hook)], cwd=repo, capture_output=True, text=True, check=False, env=env)

    assert ran.returncode == 0, ran.stdout + ran.stderr
    assert sentinel.exists(), "content chained after the guard never ran"


# --- liveness verification (D2) -------------------------------------------


def test_success_claims_verified_not_merely_installed(repo: Path) -> None:
    result = _install(repo)

    assert result.returncode == VERIFIED
    assert "verified" in result.stdout.lower()


def test_a_guard_that_exists_but_does_not_block_is_reported_not_live(repo: Path, tmp_path: Path) -> None:
    """The whole point: presence is not efficacy, and the installer must not take it on faith.

    A fake shelf whose guard script exits 0 — present, findable, executable, and
    useless. Every artifact check passes; only running it against an offending
    change tells the truth.
    """
    fake_shelf = tmp_path / "fake-shelf"
    guard = fake_shelf / "tools" / "hooks" / "forbid-local-shelf-source.py"
    guard.parent.mkdir(parents=True)
    guard.write_text("#!/usr/bin/env python3\nraise SystemExit(0)\n")
    guard.chmod(0o755)
    _use_hookspath(repo)

    result = _install(repo, shelf_home=str(fake_shelf))

    assert result.returncode != VERIFIED
    assert "not live" in (result.stdout + result.stderr).lower()


def test_unverifiable_environment_is_distinct_from_success(repo: Path, tmp_path: Path) -> None:
    """The guard's deliberate fail-open (shelf not cloned) must not read as verified.

    `HOOK` exits 0 when it cannot find the guard script, on purpose — a consumer
    without the shelf checked out should not be unable to commit. But "the hook
    declined to guard" is not "the guard works", and collapsing the two is exactly
    how a dead guard reported green.
    """
    empty_home = tmp_path / "nowhere"
    empty_home.mkdir()

    result = _install(repo, shelf_home=str(tmp_path / "absent"), home=str(empty_home))

    assert result.returncode == COULD_NOT_VERIFY
    combined = (result.stdout + result.stderr).lower()
    assert "could not" in combined or "unverified" in combined


def test_verification_does_not_touch_the_repo(repo: Path) -> None:
    """Verification runs the hook for real; it must leave no trace doing so."""
    (repo / "untracked.txt").write_text("mine\n")
    (repo / "pyproject.toml").write_text('[project]\nname = "c"\nversion = "0.2.0"\n')
    _git(repo, "add", "pyproject.toml")

    before_status = subprocess.run(["git", "-C", str(repo), "status", "--porcelain"], capture_output=True, text=True, check=True).stdout
    before_head = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout
    before_objects = sorted(p.name for p in (repo / ".git" / "objects").rglob("*") if p.is_file())

    assert _install(repo).returncode == VERIFIED

    after_status = subprocess.run(["git", "-C", str(repo), "status", "--porcelain"], capture_output=True, text=True, check=True).stdout
    after_head = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout
    after_objects = sorted(p.name for p in (repo / ".git" / "objects").rglob("*") if p.is_file())

    assert after_status == before_status, "verification changed the index or working tree"
    assert after_head == before_head
    assert after_objects == before_objects, "verification wrote objects into the repo"


def test_installed_guard_blocks_a_real_commit(repo: Path) -> None:
    """End-to-end: the property the installer now claims, exercised through git itself.

    `git commit` here must run with an explicit `SHELF_HOME`, not the ambient
    environment: the guarded hook's fallback chain (`$SHELF_HOME` -> `../shelf`
    -> `~/Workspaces/shelf`) resolved only by accident on a developer machine
    where `~/Workspaces/shelf` happens to be a real clone. CI has neither, so
    an un-scoped commit found no guard, hit the documented fail-open path, and
    let the offending commit through -- a test-environment gap, not a guard
    regression (found for real on the first CI run this repo ever had).
    """
    _use_hookspath(repo)
    assert _install(repo).returncode == VERIFIED

    (repo / "pyproject.toml").write_text(
        '[project]\nname = "c"\nversion = "0.1.0"\n\n[tool.uv.sources]\nanyllm = { path = "../shelf/packages/anyllm", editable = true }\n'
    )
    _git(repo, "add", "pyproject.toml")
    env = {**os.environ, "SHELF_HOME": str(SHELF)}
    committed = subprocess.run(["git", "-C", str(repo), "commit", "-m", "offender"], capture_output=True, text=True, check=False, env=env)

    assert committed.returncode != 0, "the offending commit was not blocked"


# --- foreign-hook diagnosis (D3) ------------------------------------------


@pytest.mark.parametrize(
    ("body", "expected"),
    [
        (_BEADS_HOOK, "beads"),
        (_PRECOMMIT_HOOK, "pre-commit"),
        (_HUSKY_HOOK, "husky"),
        (_LEFTHOOK_HOOK, "lefthook"),
    ],
)
def test_foreign_hook_is_refused_and_its_owner_named(repo: Path, body: str, expected: str) -> None:
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit").write_text(body)

    result = _install(repo)

    assert result.returncode == REFUSED
    assert expected in result.stderr.lower()
    assert (hooks / "pre-commit").read_text() == body, "refusal must not modify the foreign hook"


def test_beads_refusal_points_outside_the_managed_block(repo: Path) -> None:
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit").write_text(_BEADS_HOOK)

    result = _install(repo)

    assert "end" in result.stderr.lower(), "must say to append AFTER the END marker"


def test_unrecognized_foreign_hook_still_gets_generic_advice(repo: Path) -> None:
    hooks = _hooks_dir(repo)
    hooks.mkdir(parents=True, exist_ok=True)
    (hooks / "pre-commit").write_text(_HANDWRITTEN_HOOK)

    result = _install(repo)

    assert result.returncode == REFUSED
    assert "forbid-local-shelf-source.py" in result.stderr


def test_precommit_and_hookspath_contention_is_reported(repo: Path) -> None:
    """Each tool's documented fix silently disarms the other; say so before they hit it."""
    (repo / ".pre-commit-config.yaml").write_text("repos: []\n")
    _use_hookspath(repo)

    result = _install(repo)

    combined = (result.stdout + result.stderr).lower()
    assert "core.hookspath" in combined
    assert "pre-commit" in combined


def test_not_a_git_repository_is_reported(tmp_path: Path) -> None:
    result = _install(tmp_path)

    assert result.returncode != VERIFIED
    assert "not a git repository" in result.stderr.lower()
