"""The `hooks` operation: prek owns the hooks, configured from the blueprint recipe, bd run from it."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
from onboard.hooks import HooksOperation, config_text
from onboard.operations import Outcome


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True).stdout


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    r = tmp_path / "repo"
    r.mkdir()
    _git(r, "init", "-q")
    return r


def test_the_config_runs_bd_first_then_the_shelf_checks_then_the_gate() -> None:
    text = config_text(beads=True, python=True)
    order = [text.index(s) for s in ("bd hooks run pre-commit", "forbid-local-shelf-source", "ruff check", "entry: make check")]
    assert order == sorted(order)
    assert "default_install_hook_types" in text


def test_without_beads_or_python_the_config_carries_neither() -> None:
    text = config_text(beads=False, python=False)
    assert "bd hooks run" not in text
    assert "ruff check" not in text
    assert "forbid-local-shelf-source" in text


@pytest.mark.skipif(shutil.which("prek") is None and shutil.which("uvx") is None, reason="prek is not available")
def test_installs_prek_hooks_and_clears_bd_and_hooks_path(repo: Path) -> None:
    hooks = repo / ".git" / "hooks"
    hooks.mkdir(exist_ok=True)
    (hooks / "pre-commit").write_text("#!/bin/sh\n# --- BEGIN BEADS INTEGRATION v1.1.2 ---\n")
    _git(repo, "config", "core.hooksPath", str(repo / ".beads" / "hooks"))
    result = HooksOperation(repo, beads=False).run({})
    assert result.outcome == Outcome.APPLIED, result.message
    assert "File generated by prek" in (hooks / "pre-commit").read_text()
    assert (repo / ".pre-commit-config.yaml").is_file()


def test_a_foreign_hook_manager_is_refused_not_clobbered(repo: Path) -> None:
    hooks = repo / ".git" / "hooks"
    hooks.mkdir(exist_ok=True)
    (hooks / "pre-commit").write_text('#!/bin/sh\n. "$(dirname "$0")/_/husky.sh"\nnpm test\n')
    result = HooksOperation(repo, beads=False).run({})
    assert result.outcome == Outcome.FAILED
    assert "another hook manager owns it" in result.message
    assert "husky" in (hooks / "pre-commit").read_text()
