"""The `hooks` operation: prek owns the git hooks, configured from the blueprint recipe.

Replaces the hand-written hook installer (tools/hooks/install.py, deleted 2026-10-11). The recipe
(openspec/changes/blueprint-skill/research/hooks-and-beads.md): bd never installs hooks itself; its
five events run from `.pre-commit-config.yaml`, first, then the shelf's commit guard and ruff on staged
files, then `make check`. A failing check blocks the commit and bd still runs; bd's own injection into
another manager's hook file made a failing check stop blocking.

Append-only like the rest of onboarding: an existing `.pre-commit-config.yaml` is kept as the owner
wrote it, and the result says so; blueprint's `gate.hooks-recipe` then judges it.

Effect-assertion: after `prek install`, the installed pre-commit hook must be prek's, `core.hooksPath`
must be unset, and no bd block may be injected in the hooks folder.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .operations import Outcome, Result

_SHELF_ROOT = Path(__file__).resolve().parent.parent.parent
_RECIPE = _SHELF_ROOT / "packages" / "blueprint" / "src" / "blueprint" / "recipes" / "pre-commit-config.yaml"
_CONFIG = ".pre-commit-config.yaml"
_BEADS_MARKER = "BEGIN BEADS INTEGRATION"
_GATE_BLOCK = "- repo: local\n  hooks:\n  - id: gate\n"

# The shelf consumer's own fast checks, between bd's entries and the gate. The guard is resolved the
# same way `make guard` does it, so a consumer needs no copy of the script.
_SHELF_HOOKS = """# The shelf's commit guard and ruff on staged files (shelf onboarding).
- repo: local
  hooks:
  - id: shelf-guard
    name: no local shelf source
    entry: >-
      sh -c 'g="${SHELF_HOME:-../shelf}/tools/hooks/forbid-local-shelf-source.py";
      [ -f "$g" ] || g="$HOME/Workspaces/shelf/tools/hooks/forbid-local-shelf-source.py"; python3 "$g"'
    language: system
    always_run: true
    pass_filenames: false
    stages: [pre-commit]
  - id: ruff-check
    name: ruff check
    entry: uv run --frozen ruff check --force-exclude
    language: system
    types: [python]
    stages: [pre-commit]
  - id: ruff-format
    name: ruff format
    entry: uv run --frozen ruff format --check --force-exclude
    language: system
    types: [python]
    stages: [pre-commit]
"""


def config_text(*, beads: bool, python: bool) -> str:
    """The `.pre-commit-config.yaml` onboarding writes: the recipe, the shelf's hooks before the gate."""
    recipe = _RECIPE.read_text()
    head, gate = recipe.split(_GATE_BLOCK, 1)
    if not beads:
        head = head[: head.index("repos:")] + "repos:\n"
    shelf = _SHELF_HOOKS if python else _SHELF_HOOKS.split("  - id: ruff-check", 1)[0]
    return head + shelf + _GATE_BLOCK + gate


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, check=False)


def _prek(repo: Path) -> list[str] | None:
    local = repo / ".venv" / "bin" / "prek"
    if local.is_file():
        return [str(local)]
    if shutil.which("prek"):
        return ["prek"]
    if shutil.which("uvx"):
        return ["uvx", "prek"]
    return None


# Hook files onboarding may replace: prek's own, bd's injected ones, and the old shelf installer's.
_REPLACEABLE = ("File generated by prek", "File generated by pre-commit", _BEADS_MARKER, "shelf-guard", "shelf-lint")


def _foreign_hook(repo: Path) -> str | None:
    """The installed pre-commit hook, when another manager (husky, lefthook, a hand-written script) owns it."""
    pre_commit = _hooks_dir(repo) / "pre-commit"
    if not pre_commit.is_file():
        return None
    text = pre_commit.read_text(errors="replace")
    return None if any(marker in text for marker in _REPLACEABLE) else str(pre_commit)


def _hooks_dir(repo: Path) -> Path:
    path = Path(_git(repo, "rev-parse", "--git-path", "hooks").stdout.strip() or ".git/hooks")
    return path if path.is_absolute() else repo / path


@dataclass
class HooksOperation:
    """Writes the prek config (if absent), clears bd's own hooks and any hooksPath, runs `prek install`."""

    repo: Path
    beads: bool = True
    name: str = "hooks"
    requires: tuple[str, ...] = ()

    def run(self, _results: dict[str, Result]) -> Result:
        """Apply the recipe, install, and assert the installed hooks are prek's."""
        if _git(self.repo, "rev-parse", "--git-dir").returncode != 0:
            return Result(Outcome.COULD_NOT_APPLY, verified=False, message=f"{self.repo} is not a git repository")
        prek = _prek(self.repo)
        if prek is None:
            return Result(Outcome.COULD_NOT_APPLY, verified=False, message="prek not found: `uv tool install prek`, then re-run")

        foreign = _foreign_hook(self.repo)
        if foreign:
            return Result(
                Outcome.FAILED,
                verified=False,
                message=f"{foreign}: another hook manager owns it; move its checks into {_CONFIG}, then re-run",
            )
        config = self.repo / _CONFIG
        kept = config.exists()
        if not kept:
            config.write_text(config_text(beads=self.beads, python=(self.repo / "pyproject.toml").exists()))
        if self.beads and shutil.which("bd"):
            subprocess.run(["bd", "hooks", "uninstall"], cwd=self.repo, capture_output=True, text=True, check=False)
        _git(self.repo, "config", "--local", "--unset", "core.hooksPath")
        install = subprocess.run([*prek, "install", "--overwrite"], cwd=self.repo, capture_output=True, text=True, check=False)
        if install.returncode != 0:
            return Result(Outcome.FAILED, verified=False, message=f"prek install failed: {(install.stderr or install.stdout).strip()}")
        return _verify(self.repo, kept=kept)


def _verify(repo: Path, *, kept: bool) -> Result:
    hooks = _hooks_dir(repo)
    pre_commit = hooks / "pre-commit"
    if not pre_commit.is_file() or "File generated by prek" not in pre_commit.read_text(errors="replace"):
        return Result(Outcome.FAILED, verified=False, message=f"{pre_commit} is not prek's after `prek install`")
    injected = sorted(p.name for p in hooks.iterdir() if p.is_file() and _BEADS_MARKER in p.read_text(errors="replace"))
    if injected:
        return Result(Outcome.FAILED, verified=False, message=f"bd's block is still in {', '.join(injected)}")
    if _git(repo, "config", "--local", "core.hooksPath").stdout.strip():
        return Result(Outcome.FAILED, verified=False, message="core.hooksPath is still set")
    done = f"kept the existing {_CONFIG}" if kept else f"wrote {_CONFIG} from the blueprint recipe"
    return Result(Outcome.APPLIED, verified=True, message=f"{done}; prek installed its hooks")


if __name__ == "__main__":  # pragma: no cover - a debugging entry point
    sys.stdout.write(config_text(beads=True, python=True))
