#!/usr/bin/env python3
"""Project the flat-file ontology into human-readable indexes.

The catalog (``catalog/*.toml``), the use-cases (``use-cases/*.toml``), and the
ledger (``ledger/*.toml``) are the unit of truth (constitution I, resolution 0003).
This script DERIVES ``catalog/README.md``, ``use-cases/README.md``, and
``ledger/README.md`` from them — never hand-edit those files; run ``make catalog``.
``tests/test_catalog_projection.py`` fails if they drift, so the indexes can never
silently diverge from the files.

Load-bearing derivation: a MicroSoftware's *consumers* are NOT stored on its manifest
(that would be a shared, merge-prone field). They are computed here from the active
use-cases that point at it. A software with zero active use-cases is **orphaned** — a
decay candidate (Article VIII).
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_CATALOG_DIR = _ROOT / "catalog"
_USECASE_DIR = _ROOT / "use-cases"
_LEDGER_DIR = _ROOT / "ledger"

_BANNER = "<!-- GENERATED by tools/catalog.py from the *.toml files — do not edit; run `make catalog`. -->"


def load(directory: Path) -> list[dict[str, object]]:
    """Load every ``*.toml`` file in a directory, ordered by filename."""
    entries: list[dict[str, object]] = []
    for path in sorted(directory.glob("*.toml")):
        with path.open("rb") as handle:
            entries.append(tomllib.load(handle))
    return entries


def _cell(value: object) -> str:
    """Render a scalar or list field as one markdown table cell."""
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    return str(value)


def _active_consumers(software: str, use_cases: list[dict[str, object]]) -> list[str]:
    """The consumers with a live UseCase for a software — the derived consumer list."""
    return sorted(str(uc["consumer"]) for uc in use_cases if uc["software"] == software and uc["status"] == "active")


def render_catalog(entries: list[dict[str, object]], use_cases: list[dict[str, object]]) -> str:
    """Render the catalog manifests as a markdown index, consumers derived from use-cases."""
    header = (
        f"# Catalog — the shelf's MicroSoftware instances\n\n{_BANNER}\n\n"
        "One row per `catalog/*.toml`. Types live in [`docs/glossary.md`](../docs/glossary.md); these are "
        "instances. **Consumers are derived** from active [`use-cases/`](../use-cases/README.md) — a piece with "
        "none is *orphaned* (Article VIII). Founding set — bootstrapped, not promoted (Article VII governs new entries).\n\n"
        "| Software | Kind | Tier | Release | Status | Implementation | Consumers | Capability |\n"
        "| --- | --- | --- | --- | --- | --- | --- | --- |\n"
    )
    rows = ""
    for e in entries:
        consumers = _active_consumers(str(e["name"]), use_cases)
        consumers_cell = ", ".join(consumers) if consumers else "— **orphaned**"
        rows += (
            f"| {_cell(e['name'])} | {_cell(e['kind'])} | {_cell(e['tier'])} | {_cell(e['release'])} "
            f"| {_cell(e['status'])} | {_cell(e['implementation'])} | {consumers_cell} | {_cell(e['capability'])} |\n"
        )
    return header + rows


def render_use_cases(entries: list[dict[str, object]]) -> str:
    """Render the published dependencies (why + what) as a markdown index."""
    ordered = sorted(entries, key=lambda e: (str(e["software"]), str(e["consumer"])))
    header = (
        f"# Use-cases — every consumer's published dependency\n\n{_BANNER}\n\n"
        "One row per `use-cases/*.toml`: a consumer declares **why** it needs a piece and **what** it relies on. "
        "This is the retention claim — a piece cannot be retired while an active row points at it (the Requester "
        "controls retirement; the Owner controls shape — the two hats).\n\n"
        "| Consumer | Software | Status | Why necessary | What it needs |\n"
        "| --- | --- | --- | --- | --- |\n"
    )
    rows = "".join(
        f"| {_cell(e['consumer'])} | {_cell(e['software'])} | {_cell(e['status'])} | {_cell(e['why'])} | {_cell(e['needs'])} |\n"
        for e in ordered
    )
    return header + rows


def render_ledger(entries: list[dict[str, object]]) -> str:
    """Render the ledger events as a chronological markdown index."""
    ordered = sorted(entries, key=lambda e: int(e["seq"]))  # type: ignore[arg-type, call-overload]
    header = (
        f"# Ledger — the fitness record (append-only)\n\n{_BANNER}\n\n"
        "One row per `ledger/*.toml`: request → delivery → verdict → cost (R154). "
        "Append a file per event; never rewrite history.\n\n"
        "| Seq | Date | Event | Software | Release | Actor | Verdict | Note |\n"
        "| --- | --- | --- | --- | --- | --- | --- | --- |\n"
    )
    rows = "".join(
        f"| {_cell(e['seq'])} | {_cell(e['date'])} | {_cell(e['event'])} | {_cell(e['software'])} "
        f"| {_cell(e['release'])} | {_cell(e['actor'])} | {_cell(e.get('verdict', ''))} | {_cell(e['note'])} |\n"
        for e in ordered
    )
    return header + rows


def projections() -> dict[Path, str]:
    """Return the mapping of output path -> derived content for all indexes."""
    catalog = load(_CATALOG_DIR)
    use_cases = load(_USECASE_DIR)
    ledger = load(_LEDGER_DIR)
    return {
        _CATALOG_DIR / "README.md": render_catalog(catalog, use_cases),
        _USECASE_DIR / "README.md": render_use_cases(use_cases),
        _LEDGER_DIR / "README.md": render_ledger(ledger),
    }


def main() -> int:
    """Regenerate every derived index in place. `--check` verifies freshness instead."""
    check = "--check" in sys.argv[1:]
    stale: list[str] = []
    for path, content in projections().items():
        current = path.read_text() if path.exists() else ""
        if current == content:
            continue
        if check:
            stale.append(str(path.relative_to(_ROOT)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(_ROOT)}")
    if check and stale:
        print("stale (run `make catalog`): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
